services:
  mailserver:
    image: boky/postfix
    container_name: postfix
    restart: unless-stopped
    environment:
      - HOSTNAME=mail.example.com
      - DOMAIN=example.com
      - RELAY_NETWORKS=172.16.0.0/12 127.0.0.0/8
      - SMTP_USER=user:password
      - ALLOWED_SENDER_DOMAINS=example.com
    ports:
      - "25:25"
