version: '3.8'
services:
  db:
    image: mysql
    container_name: sqlScripts          
    restart: always
    environment:
      MYSQL_DATABASE: my_guitar_shop                      
      MYSQL_ROOT_PASSWORD: Sakshi@1234
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_db_data:/var/lib/mysql  

volumes:
  mysql_db_data:
